Repository Cenator-Timer-IPSSI/ipssi-timer-client, pull requests merged in 2020-10, with the labels that each got.

#32 [Feature] project & team view Part2
  src/components/ProjectCard.js
  src/pages/project/Project.js
  src/pages/project/ProjectUpdate.js
  src/pages/project/ProjectView.js
Labels: PR

#33 Feature pomodoro
  src/App.js
  src/pages/Home.js
  src/pages/Pomodoro.js
Labels: PR, enhancement

#37 [deployment]: prepare to deployment - Put in place Github Actions
  .github/workflows/deploy.yml
  Dockerfile
  Dockerfile-prod.yml
  docker-compose-prod.yml
Labels: MERGE
